export const ENV_IDEMPOTENCY_TABLE = 'IDEMPOTENCY_TABLE';
export const ENV_EVENT_RESULTS_TABLE = 'EVENT_RESULTS_TABLE';
export const ENV_QUEUE_URL = 'QUEUE_URL';
export const ENV_INGEST_API_KEY = 'API_KEY';
